// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/asynkron/protoactor-go/actor"
	"github.com/suzushin54/actor-based-inventory/internal/adapters"
	"github.com/suzushin54/actor-based-inventory/internal/infrastructure"
	"github.com/suzushin54/actor-based-inventory/internal/infrastructure/server"
	"github.com/suzushin54/actor-based-inventory/internal/service"
	"net/http"
	"os"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	actorSystem := NewActorSystem()
	eventPublisher, err := infrastructure.NewEventPublisher()
	if err != nil {
		return nil, err
	}
	inventoryService := service.NewInventoryService(actorSystem, eventPublisher)
	inventoryServiceHandler := adapters.NewInventoryServiceHandler(inventoryService)
	serveMux := server.ConfigureMux(inventoryServiceHandler)
	handler := provideHTTPHandler(serveMux)
	serverServer := server.NewServer(handler)
	return serverServer, nil
}

// wire.go:

func provideHTTPHandler(mux *http.ServeMux) http.Handler {
	return mux
}

func provideKafkaBrokerAddress() string {
	return os.Getenv("KAFKA_BOOTSTRAP_SERVERS")
}

func NewActorSystem() *actor.ActorSystem {
	return actor.NewActorSystem()
}
