name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 毎日0時に実行

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go mod download

      - name: Install buf
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest

      - name: Generate protobuf code
        run: buf generate

      - name: Install runn
        run: |
          curl -sSL https://runn.io/install.sh | sh

      - name: Run tests
        run: make runn
